-- Depending on your setup local/remote or one/many databases you may or may not need to select a db:
-- use my-remote-db-example;

-- After the regstration you can promote the fisrt user to admin:
-- INSERT INTO `my-remote-db-example`.`authorities` (`username`, `authority`) VALUES ('example@gmail.com', 'ROLE_ADMIN');


-- REQUIRED data for the program to run correctly 
-- genders
INSERT INTO gender (gender_id, type, enabled) VALUES (1, 'male', 1);
INSERT INTO gender (gender_id, type, enabled) VALUES (2, 'female', 1);

-- media types
INSERT INTO media_types (type_id, type, enabled) VALUES (1, 'image', 1);
INSERT INTO media_types (type_id, type, enabled) VALUES (2, 'video', 1);

-- visibilities
INSERT INTO visibilities (visibility_id, type, enabled) VALUES (1, 'public', 1);
INSERT INTO visibilities (visibility_id, type, enabled) VALUES (2, 'connections', 1);

-- connect types

INSERT INTO statuses (`status_id`, `type`, `enabled`) VALUES ('1', 'connected', '1');

INSERT INTO statuses (`status_id`, `type`, `enabled`) VALUES ('2', 'sent request', '1');

-- At least one record for the first registration:
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (1, 'Afghan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (2, 'Albanian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (3, 'Algerian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (4, 'American', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (5, 'Andorran', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (6, 'Angolan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (7, 'Antiguans', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (8, 'Argentinean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (9, 'Armenian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (10, 'Australian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (11, 'Austrian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (12, 'Azerbaijani', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (13, 'Bahamian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (14, 'Bahraini', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (15, 'Bangladeshi', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (16, 'Barbadian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (17, 'Barbudans', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (18, 'Batswana', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (19, 'Belarusian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (20, 'Belgian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (21, 'Belizean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (22, 'Beninese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (23, 'Bhutanese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (24, 'Bolivian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (25, 'Bosnian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (26, 'Brazilian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (27, 'British', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (28, 'Bruneian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (29, 'Bulgarian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (30, 'Burkinabe', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (31, 'Burmese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (32, 'Burundian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (33, 'Cambodian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (34, 'Cameroonian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (35, 'Canadian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (36, 'Cape Verdean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (37, 'Central African', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (38, 'Chadian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (39, 'Chilean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (40, 'Chinese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (41, 'Colombian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (42, 'Comoran', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (43, 'Congolese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (44, 'Costa Rican', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (45, 'Croatian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (46, 'Cuban', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (47, 'Cypriot', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (48, 'Czech', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (49, 'Danish', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (50, 'Djibouti', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (51, 'Dominican', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (52, 'Dutch', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (53, 'East Timorese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (54, 'Ecuadorean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (55, 'Egyptian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (56, 'Emirian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (57, 'Equatorial Guinean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (58, 'Eritrean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (59, 'Estonian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (60, 'Ethiopian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (61, 'Fijian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (62, 'Filipino', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (63, 'Finnish', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (64, 'French', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (65, 'Gabonese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (66, 'Gambian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (67, 'Georgian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (68, 'German', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (69, 'Ghanaian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (70, 'Greek', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (71, 'Grenadian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (72, 'Guatemalan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (73, 'Guinea-Bissauan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (74, 'Guinean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (75, 'Guyanese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (76, 'Haitian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (77, 'Herzegovinian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (78, 'Honduran', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (79, 'Hungarian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (80, 'I-Kiribati', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (81, 'Icelander', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (82, 'Indian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (83, 'Indonesian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (84, 'Iranian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (85, 'Iraqi', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (86, 'Irish', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (87, 'Israeli', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (88, 'Italian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (89, 'Ivorian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (90, 'Jamaican', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (91, 'Japanese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (92, 'Jordanian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (93, 'Kazakhstani', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (94, 'Kenyan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (95, 'Kittian and Nevisian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (96, 'Kuwaiti', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (97, 'Kyrgyz', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (98, 'Laotian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (99, 'Latvian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (100, 'Lebanese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (101, 'Liberian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (102, 'Libyan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (103, 'Liechtensteiner', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (104, 'Lithuanian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (105, 'Luxembourger', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (106, 'Macedonian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (107, 'Malagasy', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (108, 'Malawian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (109, 'Malaysian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (110, 'Maldivian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (111, 'Malian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (112, 'Maltese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (113, 'Marshallese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (114, 'Mauritanian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (115, 'Mauritian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (116, 'Mexican', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (117, 'Micronesian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (118, 'Moldovan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (119, 'Monacan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (120, 'Mongolian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (121, 'Moroccan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (122, 'Mosotho', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (123, 'Motswana', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (124, 'Mozambican', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (125, 'Namibian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (126, 'Nauruan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (127, 'Nepalese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (128, 'New Zealander', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (129, 'Ni-Vanuatu', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (130, 'Nicaraguan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (131, 'Nigerian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (132, 'Nigerien', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (133, 'North Korean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (134, 'Northern Irish', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (135, 'Norwegian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (136, 'Omani', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (137, 'Pakistani', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (138, 'Palauan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (139, 'Panamanian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (140, 'Papua New Guinean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (141, 'Paraguayan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (142, 'Peruvian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (143, 'Polish', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (144, 'Portuguese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (145, 'Qatari', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (146, 'Romanian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (147, 'Russian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (148, 'Rwandan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (149, 'Saint Lucian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (150, 'Salvadoran', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (151, 'Samoan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (152, 'San Marinese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (153, 'Sao Tomean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (154, 'Saudi', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (155, 'Scottish', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (156, 'Senegalese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (157, 'Serbian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (158, 'Seychellois', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (159, 'Sierra Leonean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (160, 'Singaporean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (161, 'Slovakian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (162, 'Slovenian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (163, 'Solomon Islander', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (164, 'Somali', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (165, 'South African', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (166, 'South Korean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (167, 'Spanish', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (168, 'Sri Lankan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (169, 'Sudanese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (170, 'Surinamer', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (171, 'Swazi', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (172, 'Swedish', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (173, 'Swiss', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (174, 'Syrian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (175, 'Taiwanese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (176, 'Tajik', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (177, 'Tanzanian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (178, 'Thai', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (179, 'Togolese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (180, 'Tongan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (181, 'Trinidadian or Tobagonian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (182, 'Tunisian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (183, 'Turkish', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (184, 'Tuvaluan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (185, 'Ugandan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (186, 'Ukrainian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (187, 'Uruguayan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (188, 'Uzbekistani', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (189, 'Venezuelan', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (190, 'Vietnamese', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (191, 'Welsh', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (192, 'Yemenite', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (193, 'Zambian', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (194, 'Zimbabwean', 1);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (195, 'Aya', 0);
INSERT INTO nationalities (nationality_id, nationality, enabled) VALUES (196, 'Babys', 0);